### ISSUE TITLE
Re-purpose site walk-through to explain use of the swipe widget

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRS-projects-map#32]
(to be completed after #29 )

**Comment by lprivette** [comment]
the swipe bar is set to load at `left: 700` which is different depending on the size of the window/screen. Because of this, the walkthrough modals/arrows could be overlapping or too far away from the swipe bar. I don't know how to bind them to be at certain location in relations to where the swipe bar loads.

It would be faster/easier to just do a 1 modal info popup when the app first loads.
